apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tunnel-credentials
data:
{{- $credentials := .Files.Glob "files/*.json" }}
{{- if $credentials }}
{{- range $path, $_ := .Files.Glob  "files/**.json" }}
  credentials.json: {{ $.Files.Get $path | b64enc }}
{{- end }}
{{- end }}
{{- $cert := .Files.Glob "files/cert.pem" }}
{{- if $cert }}
{{ (.Files.Glob "files/cert.pem").AsSecrets | indent 2 }}
{{- end }}